/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ttt;

import ttt.models.Player;
import ttt.models.Token;
import ttt.tictactoe.BasicGameController;
import ttt.tictactoe.player.BasicAIPlayerController;
import ttt.tictactoe.player.BasicHumanPlayerController;
import ttt.tictactoe.player.BasicPlayerController;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        BasicPlayerController player1 = BasicAIPlayerController.of(Token.X);
//        PlayerController player2 = RandomPlayerController.of(Token.O);
        BasicPlayerController player2 = BasicHumanPlayerController.of(Player.of(Token.O, ""), scanner);

        BasicGameController game = BasicGameController.of(player1, player2);
        game.play();
        scanner.close();
    }
}
