/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ttt;

import ttt.models.Player;
import ttt.models.Token;
import ttt.original.GameController;
import ttt.original.player.AIPlayerController;
import ttt.original.player.HumanPlayerController;
import ttt.original.player.PlayerController;
import ttt.original.player.RandomPlayerController;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        PlayerController player1 = AIPlayerController.of(Token.X);
//        PlayerController player2 = RandomPlayerController.of(Token.O);
        PlayerController player2 = HumanPlayerController.of(Player.of(Token.O, ""), scanner);

        GameController game = GameController.of(player1, player2);
        game.play();
        scanner.close();
    }
}
